// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsRemIp5PMcrpn-64rhEqXbMzx-Pu1Lho',
    appId: '1:190685915441:web:ce14cdc7541bf8fe4ea810',
    messagingSenderId: '190685915441',
    projectId: 'movie-58dc9',
    authDomain: 'movie-58dc9.firebaseapp.com',
    storageBucket: 'movie-58dc9.firebasestorage.app',
    measurementId: 'G-L7P9SDD9BH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNwE0xTlsaE7K55AGdAQ5AZeCjoeS8fOA',
    appId: '1:190685915441:android:4d4e2c1df142533b4ea810',
    messagingSenderId: '190685915441',
    projectId: 'movie-58dc9',
    storageBucket: 'movie-58dc9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJviHkI7s-vpJdyb_OeNc8zdmbmVVDNy0',
    appId: '1:190685915441:ios:bd34cbb3cdefbf824ea810',
    messagingSenderId: '190685915441',
    projectId: 'movie-58dc9',
    storageBucket: 'movie-58dc9.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJviHkI7s-vpJdyb_OeNc8zdmbmVVDNy0',
    appId: '1:190685915441:ios:bd34cbb3cdefbf824ea810',
    messagingSenderId: '190685915441',
    projectId: 'movie-58dc9',
    storageBucket: 'movie-58dc9.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsRemIp5PMcrpn-64rhEqXbMzx-Pu1Lho',
    appId: '1:190685915441:web:1950934ea53043404ea810',
    messagingSenderId: '190685915441',
    projectId: 'movie-58dc9',
    authDomain: 'movie-58dc9.firebaseapp.com',
    storageBucket: 'movie-58dc9.firebasestorage.app',
    measurementId: 'G-HMWSX9RCMV',
  );
}
