const Map<String, String> arTranslations = {
  'app_title': 'تطبيق موفي',
  'or': 'أو',
  'login': 'تسجيل الدخول',
  'register': 'إنشاء حساب',
  'email': 'البريد الإلكتروني',
  'password': 'كلمة المرور',
  'cancel': 'إلغاء',
  'retry': 'إعادة المحاولة',

  'forget_password_q': 'نسيت كلمة المرور؟',
  'dont_have_account': 'ليس لديك حساب؟',
  'create_one': 'إنشاء حساب جديد',
  'login_with_google': 'تسجيل الدخول بجوجل',
  'register_with_google': 'التسجيل بواسطة جوجل',
  'welcome_back': 'مرحباً بعودتك',
  'please_enter_email': 'يرجى إدخال البريد الإلكتروني',
  'please_enter_valid_email': 'يرجى إدخال بريد إلكتروني صالح',
  'please_enter_password': 'يرجى إدخال كلمة المرور',
  'password_min_length': 'كلمة المرور يجب أن لا تقل عن 6 أحرف',

  'avatar': 'الصورة الرمزية',
  'name': 'الاسم',
  'confirm_password': 'تأكيد كلمة المرور',
  'phone_number': 'رقم الهاتف',
  'create_account': 'إنشاء الحساب',
  'already_have_account': 'لديك حساب بالفعل؟',
  'please_enter_name': 'يرجى إدخال الاسم',
  'name_min_length': 'الاسم يجب أن لا يقل عن 3 أحرف',
  'please_confirm_password': 'يرجى تأكيد كلمة المرور',
  'passwords_not_match': 'كلمتا المرور غير متطابقتين',
  'please_enter_phone': 'يرجى إدخال رقم الهاتف',
  'phone_min_length': 'أدخل رقم هاتف صالح (10 أرقام على الأقل)',
  'register_success_msg': 'تم إنشاء الحساب بنجاح! يرجى تسجيل الدخول',

  'forget_password': 'نسيت كلمة المرور',
  'verify_email': 'تأكيد البريد الإلكتروني',
  'password_reset_sent_to': 'تم إرسال رابط استعادة كلمة المرور إلى',
  'check_inbox': 'تفقد بريدك الوارد!',

  'home': 'الرئيسية',
  'search': 'البحث',
  'browse': 'تصفح',
  'profile': 'حسابي',
  'watch_list': 'قائمة المشاهدة',
  'history': 'السجل',
  'wish_list': 'المفضلة',

  'action': 'أكشن',
  'available_now': 'متاح الان',
  'watch_now': 'شاهد الان',
  'see_more': 'عرض المزيد ←',
  'no_movies_available': 'لا توجد أفلام متاحة حالياً',
  'search_movies_hint': 'ابحث عن أفلام...',
  'no_movies_found': 'لم يتم العثور على أي أفلام',
  'try_searching_keyword': 'جرب البحث بكلمة مفتاحية أخرى',
  'no_movies_for_genre': 'لا توجد أفلام لتصنيف',

  'edit_profile': 'تعديل الحساب',
  'exit': 'خروج',
  'exit_app': 'تسجيل الخروج',
  'exit_confirm_msg': 'هل أنت متأكد من رغبتك في تسجيل الخروج من حسابك؟',
  'delete_account': 'حذف الحساب',
  'delete_confirm_msg':
      'هل أنت متأكد من حذف الحساب نهائياً؟ لا يمكن التراجع عن هذا الإجراء.',
  'delete': 'حذف',
  'pick_avatar': 'اختر الصورة الرمزية',
  'enter_your_name': 'أدخل اسمك',
  'enter_your_phone': 'أدخل رقم الهاتف',
  'reset_password': 'إعادة تعيين كلمة المرور',
  'update_data': 'تحديث البيانات',
  'updating': 'جاري التحديث...',
  'no_watchlist_movies': 'لا توجد أفلام في قائمة المشاهدة بعد',
  'no_history_movies': 'لا يوجد سجل مشاهدة بعد',
  'name_cannot_be_empty': 'لا يمكن ترك الاسم فارغاً',
  'profile_updated_success': 'تم تحديث البيانات بنجاح!',

  'watch': 'مشاهدة',
  'similar': 'أفلام مشابهة',
  'summary': 'القصة والتفاصيل',
  'cast': 'طاقم العمل',
  'genres': 'التصنيفات',
  'screenshots': 'لقطات من الفيلم',
  'name_label': 'الاسم',
  'character_label': 'الشخصية',
  'no_summary_available':
      'لا يوجد ملخص متاح حالياً لهذا العمل.',
  'added_to_watchlist': 'تمت إضافة "{title}" إلى قائمة المشاهدة',
  'removed_from_watchlist': 'تمت إزالة "{title}" من قائمة المشاهدة',
  'added_to_wishlist': 'تمت إضافة "{title}" إلى المفضلة',
  'removed_from_wishlist': 'تمت إزالة "{title}" من المفضلة',
  'playing_movie': 'جاري تشغيل "{title}"...',
  'watching_movie': 'جاري مشاهدة "{title}"...',
};

const Map<String, String> arGenres = {
  'action': 'أكشن',
  'adventure': 'مغامرة',
  'animation': 'رسوم متحركة',
  'comedy': 'كوميديا',
  'crime': 'جريمة',
  'documentary': 'وثائقي',
  'drama': 'دراما',
  'family': 'عائلي',
  'fantasy': 'فانتازيا',
  'history': 'تاريخي',
  'horror': 'رعب',
  'music': 'موسيقى',
  'musical': 'غنائي',
  'mystery': 'غموض',
  'romance': 'رومانسي',
  'sci-fi': 'خيال علمي',
  'science fiction': 'خيال علمي',
  'sport': 'رياضي',
  'thriller': 'إثارة',
  'war': 'حرب',
  'western': 'ويسترن',
  'biography': 'سيرة ذاتية',
  'film-noir': 'فيلم نوار',
  'short': 'قصير',
  'news': 'أخبار',
  'reality-tv': 'تلفزيون الواقع',
  'talk-show': 'برنامج حواري',
  'game-show': 'مسابقات',
};
