const Map<String, String> enTranslations = {
  'app_title': 'Route Movie App',
  'or': 'OR',
  'login': 'Login',
  'register': 'Register',
  'email': 'Email',
  'password': 'Password',
  'cancel': 'Cancel',
  'retry': 'Retry',

  'forget_password_q': 'Forget Password ?',
  'dont_have_account': 'Don’t Have Account ?',
  'create_one': 'Create One',
  'login_with_google': 'Login With Google',
  'register_with_google': 'Register With Google',
  'welcome_back': 'Welcome back',
  'please_enter_email': 'Please enter your email',
  'please_enter_valid_email': 'Please enter a valid email address',
  'please_enter_password': 'Please enter your password',
  'password_min_length': 'Password must be at least 6 characters',

  'avatar': 'Avatar',
  'name': 'Name',
  'confirm_password': 'Confirm Password',
  'phone_number': 'Phone Number',
  'create_account': 'Create Account',
  'already_have_account': 'Already Have Account ?',
  'please_enter_name': 'Please enter your name',
  'name_min_length': 'Name must be at least 3 characters',
  'please_confirm_password': 'Please confirm your password',
  'passwords_not_match': 'Passwords do not match',
  'please_enter_phone': 'Please enter your phone number',
  'phone_min_length': 'Enter a valid phone number (min 10 digits)',
  'register_success_msg': 'please login with your recently added email',

  'forget_password': 'Forget Password',
  'verify_email': 'Verify Email',
  'password_reset_sent_to': 'Password reset email sent to',
  'check_inbox': 'Check your inbox!',

  'home': 'Home',
  'search': 'Search',
  'browse': 'Browse',
  'profile': 'Profile',
  'watch_list': 'Watch List',
  'history': 'History',
  'wish_list': 'Wish List',

  'action': 'Action',
  'available_now': 'Available Now',
  'watch_now': 'Watch Now',
  'see_more': 'See More →',
  'no_movies_available': 'No movies available',
  'search_movies_hint': 'Search movies...',
  'no_movies_found': 'No movies found',
  'try_searching_keyword': 'Try searching with another keyword',
  'no_movies_for_genre': 'No movies found for',

  'edit_profile': 'Edit Profile',
  'exit': 'Exit',
  'exit_app': 'Exit App',
  'exit_confirm_msg': 'Are you sure you want to log out of your account?',
  'delete_account': 'Delete Account',
  'delete_confirm_msg':
      'Are you sure you want to delete your account? This action cannot be undone.',
  'delete': 'Delete',
  'pick_avatar': 'Pick Avatar',
  'enter_your_name': 'Enter your name',
  'enter_your_phone': 'Enter your phone number',
  'reset_password': 'Reset Password',
  'update_data': 'Update Data',
  'updating': 'Updating...',
  'no_watchlist_movies': 'No movies in your watch list yet',
  'no_history_movies': 'No watch history yet',
  'name_cannot_be_empty': 'Name cannot be empty',
  'profile_updated_success': 'Profile updated successfully!',

  'watch': 'Watch',
  'similar': 'Similar',
  'summary': 'Summary',
  'cast': 'Cast',
  'genres': 'Genres',
  'screenshots': 'Screenshots',
  'name_label': 'Name',
  'character_label': 'Character',
  'no_summary_available':
      'No detailed summary is currently available for this title.',
  'added_to_watchlist': 'Added "{title}" to Watch List',
  'removed_from_watchlist': 'Removed "{title}" from Watch List',
  'added_to_wishlist': 'Added "{title}" to Wish List',
  'removed_from_wishlist': 'Removed "{title}" from Wish List',
  'playing_movie': 'Playing "{title}"...',
  'watching_movie': 'Watching "{title}"...',
};
